version: '3.8'

services:

  # PHP service 
  php: 
    build: 
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    depends_on:
      - database
      - redis 
      - node

  # Database server
  database:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          interval: 10s
          timeout: 5s
          retries: 5


  # Redis Server
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - 6379:6379
  
  # Node
  node:
    build: 
      context: .
      target: node
    volumes:
      # - .:/usr/src
      # - .:/usr/src
      # - ./node_modules:/usr/src/node_modules
      - .:/var/www
      - /var/www/node_modules
    tty: true
    command: npm run dev
    ports:
      - "3000:3000"  # Port 3000 for Vite server (assuming default Vite port)


volumes:
  db-data: ~